name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: avsm/setup-ocaml@master
        with:
          ocaml-compiler: 4.13.1

      - run: opam install --yes --deps-only --with-test .
      - run: opam exec -- dune build
      - run: opam exec -- dune build @test/runtest
